kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: 'slack'
      group_by: ['alertname', 'priority', 'cluster', 'job']
      group_wait: 5m
      repeat_interval: 24h
      routes:
        - receiver: slack
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 5m
          repeat_interval: 24h
        
    receivers:
    - name: slack
      slack_configs:
      - api_url: [your webhoock url]
        channel: '#your-group'